version: "3.9"
services:
  frontend-senior-project:
    build: ./frontend
    ports:
      - "${FRONTEND}:${FRONTEND}"
    volumes:
      - ./frontend/app:/app:cached
    environment:
      ENV NODE_ENV: development
  backend-senior-project:
    build: ./backend
    ports:
      - "${BACKEND}:${BACKEND}"
    volumes:
      - ./backend/app:/app:cached
    environment:
      ENV NODE_ENV: development
  mongo:
    image: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
          - db_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
