version: "3.9"
services:
  frontend-senior-project:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/app:cached
    environment:
      ENV NODE_ENV: development
  backend-senior-project:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app:/app:cached
    environment:
      ENV NODE_ENV: development
