version: "3.9"
services:
  frontend-senior-project:
    stdin_open: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:cached
    environment:
      ENV NODE_ENV: development
    working_dir: /app
    # command: yarn install
